name = "CompartmentalParticleFilters"
uuid = "5d57c78f-ea6e-4c02-9166-0483d286b5c9"
authors = ["Annika Helverson"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
